version: "3" 
services: 
  app: ##posso por o nome que eu quiser
    build: . 
    container_name: nodewithdocker
    entrypoint: ./.docker.entrypoint.sh
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/app 